/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface UvalibFooter {
    '_currentYear': string;
  }
  interface UvalibFooterAttributes extends StencilHTMLAttributes {
    '_currentYear'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'UvalibFooter': Components.UvalibFooter;
  }

  interface StencilIntrinsicElements {
    'uvalib-footer': Components.UvalibFooterAttributes;
  }


  interface HTMLUvalibFooterElement extends Components.UvalibFooter, HTMLStencilElement {}
  var HTMLUvalibFooterElement: {
    prototype: HTMLUvalibFooterElement;
    new (): HTMLUvalibFooterElement;
  };

  interface HTMLElementTagNameMap {
    'uvalib-footer': HTMLUvalibFooterElement
  }

  interface ElementTagNameMap {
    'uvalib-footer': HTMLUvalibFooterElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
